### ISSUE TITLE
panic if you provide empty string on stdin without --no-trim

### ISSUE THREAD

**Issue by mikesimons** [mikesimons/envelope#7]
**Replicate**: `echo "" | envelope-dev encrypt --in-place --key=test.test file.yml`
**Expected result**: file.yml contains encrypted empty string at test.test
**Actual result**:
```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
io/ioutil.readAll.func1(0xc00011f238)
	/usr/local/Cellar/go/1.11.2/libexec/src/io/ioutil/ioutil.go:30 +0x105
panic(0x151cbe0, 0x19de170)
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/panic.go:513 +0x1b9
main.(*TrimReader).Read(0xc000057b40, 0xc000190c00, 0x200, 0x200, 0x200, 0x200, 0xc000190c00)
	/Users/Mike/go/src/github.com/mikesimons/envelope/cmd/envelope/shared.go:99 +0xfb
bytes.(*Buffer).ReadFrom(0xc0001a73b0, 0x1660f20, 0xc000057b40, 0xc000028e90, 0x7ffeefbffa34, 0x4)
	/usr/local/Cellar/go/1.11.2/libexec/src/bytes/buffer.go:206 +0xb4
io/ioutil.readAll(0x1660f20, 0xc000057b40, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.11.2/libexec/src/io/ioutil/ioutil.go:36 +0xb5
io/ioutil.ReadAll(0x1660f20, 0xc000057b40, 0x4, 0xc0001a6620, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.11.2/libexec/src/io/ioutil/ioutil.go:45 +0x3e
github.com/mikesimons/envelope.(*Envelope).EncryptWithOpts(0xc000180870, 0x7ffeefbffa34, 0x4, 0x1660f20, 0xc000057b40, 0x15bb5a0, 0x1, 0xc00000e120, 0x0, 0x0, ...)
	/Users/Mike/go/src/github.com/mikesimons/envelope/encrypt.go:35 +0x9b
github.com/mikesimons/envelope.(*Envelope).InjectEncrypted(0xc000180870, 0x7ffeefbffa34, 0x4, 0x1661260, 0xc00000e120, 0x7ffeefbffa3f, 0xf, 0x1660f20, 0xc000057b40, 0x159d928, ...)
	/Users/Mike/go/src/github.com/mikesimons/envelope/inject.go:30 +0x18a
main.encryptCommand.func1(0xc0000e46e0, 0x10100, 0xc0000e46e0)
	/Users/Mike/go/src/github.com/mikesimons/envelope/cmd/envelope/encrypt.go:119 +0x391
github.com/mikesimons/envelope/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x14f84c0, 0x15bbb10, 0xc0000e46e0, 0xc000098b00, 0x0)
	/Users/Mike/go/src/github.com/mikesimons/envelope/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/mikesimons/envelope/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x159e792, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15a6223, 0x18, 0x0, ...)
	/Users/Mike/go/src/github.com/mikesimons/envelope/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0x990
github.com/mikesimons/envelope/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00013d380, 0xc00001e080, 0x8, 0x8, 0x0, 0x0)
	/Users/Mike/go/src/github.com/mikesimons/envelope/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x687
main.main()
	/Users/Mike/go/src/github.com/mikesimons/envelope/cmd/envelope/main.go:44 +0x425
```

**Comment by mikesimons** [comment]
Bug is here: https://github.com/mikesimons/envelope/blob/master/cmd/envelope/shared.go#L99
